### ISSUE TITLE
If observe() callback function is used, generate() returns no patches 

### ISSUE THREAD

**Issue by sandrokeil** [Starcounter-Jack/JSON-Patch#119] opened 2016-09-02 05:35 UTC
Let's start with an example:

``` js
var diffObserver = jsonpatch.observe( _formData, function( patch ) {
    console.log(patch);
} );

// later in save()
self.save = function() {
    // patches is empty
    var patches = jsonpatch.generate(diffObserver); 
}
```

The problem is, that the callback function tracks every change, but if you set a value and remove it again, two patches (add and remove) are registered through the callback function, but nothing has changed. I need to know if something has changed, but only want the result of the changes and not every history of the changes. 

Why returns `generate` no patches, if a callback function is used? Tested with version 1.0.0.

A workaround is to use `compare`, but I'm not quite happy with that.

**Comment by tomalec** [comment] 2016-09-10 21:21
Sorry, but I don't quite get it.
In your code example there is no change being made. Even if there are add+remove of the same node, the result of `generate` will show you the result of those two changes - noting changed - no patches.

Could you provide jsfiddle with an example?

**Comment by sandrokeil** [comment] 2016-09-12 14:50
Ok, maybe I've a bug in my code. I will check this, but it could take some days. Thanks.

**Comment by tomalec** [comment] 2016-11-14 17:48
I'm closing it. Feel free to re-open, once you will be able to reproduce it.

**Closed by tomalec** 2016-11-14 17:48 UTC

**Comment by NicolasLiveris** [comment] 2018-12-02 18:45
Hi !

I was able to reproduce the problem in a stackblitz. This one is exactly as @sandrokeil described it.

https://json-patch-observe-issue.stackblitz.io

Thank, for help.

**Comment by alshakero** [comment] 2018-12-03 15:00
Maybe we need to document this but when you pass a callback to observe `generate` will not work anymore since you're getting interim changes.

If you want to use `generate` you may remove the callback from `observe` and it will work as expected.

**Comment by NicolasLiveris** [comment] 2018-12-04 06:02
Hi, @alshakero 

So if I want to use the callback I have to generate the patch myself?

Thanks.

**Comment by NicolasLiveris** [comment] 2018-12-04 12:44
That's understood. Thank you for those clarifications and for your time.

**Comment by alshakero** [comment] 2018-12-04 13:57
My pleasure!

**Comment by alshakero** [comment] 2018-12-04 13:58
Worth mentioning that the callback will always give you an array (a patch, not a single operation).
