### ISSUE TITLE
Compare function doesn't produce any patches when dates differ

### ISSUE THREAD

**Issue by charlieamer** [Starcounter-Jack/JSON-Patch#130] opened 2016-11-14 19:28 UTC
The following code shows what I am talking about:
```javascript
var fastjsonpatch = require("fast-json-patch");
a = {test: new Date()};
tmp = new Date();
tmp.setYear(2000);
b = {test: tmp};
console.log(fastjsonpatch.compare(a,b));
```
The code above right now produces 
```json
[]
```
But it should produce
```json
[{"op": "replace", "path": "/test", "value": ...}]
```

**Comment by MarkHerhold** [comment] 2016-11-17 19:33
Duplicate of https://github.com/Starcounter-Jack/JSON-Patch/issues/122

**Comment by tomalec** [comment] 2016-11-21 16:33
@charlieamer If there is anything more you would like to discuss, feel free to re-open #122 and continue there.

**Closed by tomalec** 2016-11-21 16:33 UTC
